bunny:
  name: bunnylol
  url: http://localhost:8000/
g:
  name: Google
  url: https://www.google.com/search?q={}
gh:
  name: Github
  url: https://github.com/{}
ghs:
  url: https://github.com/search?q={}
  name: Github Search
